[package]
name = "tauri-dialog-sys"
version = "0.1.0"
authors = ["Lucas Nogueira <lucas@tauri.studio>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/tauri-apps/tauri-dialog-rs"
description = "Rust bindings to Boxer"

[build-dependencies]
cc = "1"
pkg-config = "0.3"